sudo: false
language: python

branches:
  only:
  - master

cache:
  - pip

install:
  - "python -m pip install -U pip"
  - "python -m pip install -U setuptools"
  - "python -m pip install -U tox"

script:
  - "tox"

after_success:
  - "python -m pip install -U codecov"
  - "codecov"

matrix:
  include:
    - env: TOXENV=py27
      python: 2.7
    - env: TOXENV=py34
      python: 3.4
    - env: TOXENV=py35
      python: 3.5
    - env: TOXENV=py35
      python: 3.5-dev
    - env: TOXENV=py36
      python: 3.6
    - env: TOXENV=py36
      python: 3.6-dev
    - env: TOXENV=py37
      python: 3.7
      dist: xenial
    - env: TOXENV=py37
      python: 3.7-dev
      dist: xenial

    - env: TOXENV=lint
      python: 3.6
